#!/bin/bash
# SPDX-FileCopyrightText: 2026 Intensivate, Inc.
# SPDX-License-Identifier: BSD-2-Clause
#
# copies_dispatch.sh NHARTS -- prints the RATE_MODE=copies dispatcher: hart N
# runs private copy h<N>_ of the whole program (see build.sh).
NH=$1; PORT=${PORT:-program}
{
  echo "/* Generated by copies_dispatch.sh: $PORT rate image, $NH copies. */"
  echo "#include <stdint.h>"
  echo "#include <stdio.h>"
  echo "#include <fcntl.h>"
  echo "#include \"util.h\""
  echo "void tohost_exit(uintptr_t code) __attribute__((noreturn));"
  echo "void printstr(const char* s);"
  for ((h=0; h<NH; h++)); do
    echo "extern int h${h}_thread_entry(int cid, int nc);"
    echo "extern void h${h}_exit(int code) __attribute__((noreturn));"
    echo "extern int h${h}_open(const char *path, int flags, ...);"
    echo "extern void h${h}_bm_redirect_std(int fd, long host_fd);"
    echo "extern void (*__start_h${h}_init_array[])(void) __attribute__((weak));"
    echo "extern void (*__stop_h${h}_init_array[])(void) __attribute__((weak));"
  done
  cat <<'EOF'

/* Per-hart counters over the whole copy (entry to _exit), reported as
   R_<hart>: lines at exit -- the rate metric's per-copy cycles/instructions. */
static uint64_t start_cycle[NHARTS], start_instret[NHARTS];

static void put_dec(char **p, uint64_t v)
{
  char d[24]; int n = 0;
  do { d[n++] = '0' + v % 10; v /= 10; } while (v);
  while (n) *(*p)++ = d[--n];
}

void __attribute__((noreturn)) _exit(int code)
{
  uint64_t c = read_csr(mcycle), i = read_csr(minstret);
  int h = read_csr(mhartid);
  char buf[96], *p = buf;
  const char *s;
  for (s = "R_"; *s; ) *p++ = *s++;
  put_dec(&p, h);
  for (s = ": copy_mcycle = "; *s; ) *p++ = *s++;
  put_dec(&p, c - start_cycle[h]);
  for (s = " copy_minstret = "; *s; ) *p++ = *s++;
  put_dec(&p, i - start_instret[h]);
  for (s = " exit = "; *s; ) *p++ = *s++;
  put_dec(&p, (uint64_t)(unsigned)code);
  *p++ = '\n'; *p = 0;
  printstr(buf);
  tohost_exit(code);
}

/* Each copy's fds 1 and 2 go to its own files in the emulator's working
   directory (fesvr opens them host-side), as each copy of a rate run writes
   its own output, so every copy's result can be checked on its own. fesvr's
   fd table is shared by all harts, so a copy can't close and reopen fds 1
   and 2; instead it opens its files (they get fds of their own) and points
   its private fd 1/2 at them (bm_redirect_std, htif_syscalls.c). That covers
   both the C streams and programs that write(2) directly (xlisp). The
   runtime's own console output (R_ lines, trap reports) is unaffected. The
   counters start after that, at the copy's own entry point. */
#define REDIRECT(h, out, err) do { \
    h##_bm_redirect_std(1, h##_open(out, O_WRONLY | O_CREAT | O_TRUNC, 0644)); \
    h##_bm_redirect_std(2, h##_open(err, O_WRONLY | O_CREAT | O_TRUNC, 0644)); } while (0)
/* A copy's static constructors (e.g. C++ iostream's) run first, as a C
   runtime's startup would; riscv-tests' own crt.S runs none. */
#define CTORS(h) do { void (**p_)(void); \
    for (p_ = __start_h##h##_init_array; p_ < __stop_h##h##_init_array; p_++) (*p_)(); } while (0)
#define START(h) do { start_cycle[h] = read_csr(mcycle); \
                      start_instret[h] = read_csr(minstret); } while (0)

int thread_entry(int cid, int nc)
{
  switch (cid) {
EOF
  for ((h=0; h<NH; h++)); do
    hh=$(printf %02d $h)
    echo "  case $h:"
    echo "    CTORS($h);"
    echo "    REDIRECT(h$h, \"hart$hh.out\", \"hart$hh.err\");"
    echo "    START($h);"
    echo "    h${h}_exit(h${h}_thread_entry(cid, nc));"
  done
  cat <<'EOF'
  }
  return 1;
}
EOF
}
