instname = riscv-tests
instbasedir = $(UCB_VLSI_HOME)/install

tests = coh_checker amoadd_simple amoadd amo-megazord
tests += interrupts workqueue combined fail amo-stall

tests += hello

include ../Makefrag-baremetal
